name: Test Html File

on:
  workflow_dispatch:



jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4

      - name: Print index.html file
        run: |
          cd JavaMaven
          cat index.html

