
name: secretkey variables test

on:
  workflow_dispatch:
env:
  ACTIONS_STEP_DEBUG: true

jobs:
  test-secret-variables:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name : " secret variables test "
        run :
          echo "Secret value : ${{ secrets.testkey }}"